apiVersion: v1
kind: ConfigMap
metadata:
  name: gestor-ordenes-config
  namespace: gestor-ordenes
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC_ORDENES: "ordenes"
  DYNAMO_TABLE_ORDENES: "ordenes"
  AWS_REGION: "us-east-1"
