apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-matcher
  namespace: gestor-ordenes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-matcher
  template:
    metadata:
      labels:
        app: consumer-matcher
    spec:
      containers:
        - name: consumer
          image: gestor-ordenes-consumer-matcher:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: gestor-ordenes-config
