apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gestor-ordenes

resources:
  - namespace.yaml
  - configmap.yaml
  - kafka.yaml
  - localstack.yaml
  - api.yaml
  - consumer-persistencia.yaml
  - consumer-matcher.yaml
