apiVersion: v1
kind: Service
metadata:
  name: localstack-service
  namespace: gestor-ordenes
spec:
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: gestor-ordenes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: dynamodb
            - name: DEFAULT_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test
          readinessProbe:
            tcpSocket:
              port: 4566
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 4566
            initialDelaySeconds: 20
            periodSeconds: 10
